### ISSUE TITLE
Tamil Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ta.reactjs.org#1]
## Maintainer List

* @pavinthan
* @ratheeps
* @majus28
* @getCodePanda
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@pavinthan)
* [ ] Tutorial (@majus28)

### Basics

* [ ] Hello World (@sarvabowmen, @cvaijothi)
* [ ] Introducing JSX (@sbkrish)
* [ ] Rendering Elements (@Madhust)
* [x] Components and Props (@Madhust)
* [ ] State and Lifecycle (@Ananthakr)
* [ ] Handling Events (@Pachiyappan)
* [ ] Conditional Rendering (@dhirajsriram)
* [ ] Lists and Keys (@puviz)
* [x] Forms (@nivedha1)
* [ ] Lifting State Up (@satheeshwaran)
* [ ] Composition vs Inheritance (@mtamilcse92)
* [ ] Thinking in React (@logesh-kumar)

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml (@pavinthan)
* [ ] docs/nav.yml (@pavinthan)

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@cvaijothi)
* [ ] Add React to a Website (@praveenscience)
* [ ] Create a New React App (@praveenscience)
* [x] CDN Links (@rajakvk)

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks (@klsv07)
  * [ ] Hooks at a Glance (@kasthuriraajan) 
  * [ ] Using the State Hook (@KiruthikaThangamuthu)
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks (@mithelan)
  * [ ] Building Your Own Hooks (@mtamilcse92)
  * [ ] Hooks API Reference (@pradheepap)
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility (@Elcomerz)
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components (@saran-io)
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community (@pavinthan)

**Comment by tesseralis** [comment]
@pavinthan, @ratheeps, @majus28, @GetCodePanda please use this issue to keep track of your progress! Let me know if you need any help or have any questions.

**Comment by pavinthan** [comment]
Sure @tesseralis and thank you for your support 🙏

**Comment by ratheeps** [comment]
Sure @tesseralis  Thank you for your support.

**Comment by tesseralis** [comment]
@pavinthan, @ratheeps, @majus28, @GetCodePanda how's it going? Have you started working on translating any of the pages? Please let me know if you need any help.

**Comment by pavinthan** [comment]
@tesseralis Yah, we are working on Home page content review for now, let you know once we done it and if any needs.

**Comment by sarvabowmen** [comment]
Hey guys, I would like to contribute, can i pick one?

**Comment by tesseralis** [comment]
@sarvabowmen go ahead and choose something under "core pages"

**Comment by pavinthan** [comment]
Thanks @sarvabowmen as @tesseralis suggested please select any of core pages and let us know, and please use https://react-translations.slack.com this slack workspace to keep in touch.

**Comment by greensand** [comment]
Very much interested to contribute. How to do i get access to the  [slack board](https://react-translations.slack.com) ?

**Comment by pavinthan** [comment]
@greensand please select any "Basics" pages to start contribute and Here's the link for the invitations: [https://rt-slack.herokuapp.com](https://rt-slack.herokuapp.com)

**Comment by sarvabowmen** [comment]
Sure

**Comment by sarvabowmen** [comment]
@pavinthan @tesseralis i can take the home page, can you please update the list

**Comment by majus28** [comment]
> @pavinthan @tesseralis i can take the Hello world, can you please update the list

@sarvabowmen The page is assigned to you.
Thanks.

**Comment by m-sureshraj** [comment]
Hi,
I would like to contribute to this translation effort. I can take the `CDN Links` page under **Installation** section as my first task.

**Comment by pavinthan** [comment]
@m-sureshraj sure go head with that please. thanks 🙏

**Comment by sarvabowmen** [comment]
Thanks

**Comment by Madhust** [comment]
@pavinthan I would like to contribute. Could you please assign me the **Basic -> Components and Props** topic to me?

**Comment by pavinthan** [comment]
thanks @Madhust, go ahead with that please.

**Comment by sbkrish** [comment]
Hi @pavinthan , 
I would like to contribute in this process. How can I join with this community?

Thanks.

**Comment by ratheeps** [comment]
Hi @sbkrish 
Please fork this repository, and update your changes, then create the pull request.
Thanks

**Comment by sbkrish** [comment]
Thanks @ratheeps , I would like to take **Introducing JSX** from Basics.

**Comment by ratheeps** [comment]
Thanks, @sbkrish,  go ahead with that, please.

**Comment by nivedha1** [comment]
Hi. I wish to contribute. I wish to take up Forms topic from Basics.

**Comment by ratheeps** [comment]
Hi @nivedha1
Thanks for your shown interesting, go ahead with that, please

**Comment by velmuruganfrontend** [comment]
Hi Team, 
Very much interested to contribute, How to join this community.

**Comment by pavinthan** [comment]
Hey @velmuruganfrontend, thanks for your interest, could you please pick any unassigned items from the list and start to contribute.

**Comment by praveenscience** [comment]
Hi @tesseralis, I am interested and can start contributing to one of the pages. May I start with the following pages?

- Add React to a Website
- Create a New React App

Let me know. Also, I am [Praveen Kumar Purushothaman](https://praveen.science/). 😊

**Comment by pavinthan** [comment]
@praveenscience please go go ahead with your selections, thanks.

**Comment by prasathbuilds** [comment]
Hi, I am interested and would like to contribute.

**Comment by praveenscience** [comment]
@pavinthan Can you invite me to the React JS slack group?

**Comment by pavinthan** [comment]
@prasathbuilds  you could select any unassigned items from this issue description to start translate and let us know what is your choose to pin the item for you.

@praveenscience here's the link for the invitations: [https://rt-slack.herokuapp.com](https://rt-slack.herokuapp.com)

Thanks

**Comment by praveenscience** [comment]
@pavinthan I did try that, but it gave me this error:

![image](https://user-images.githubusercontent.com/1830380/56817852-46681c80-683e-11e9-9ca2-ae46c1af65ba.png)

SlackIn is a good alternative I suppose.

**Comment by praveenscience** [comment]
@tesseralis Please update the *Add React to a Website* to in progress. Will try to deliver both by Monday. 😇

**Comment by praveenscience** [comment]
@tesseralis Please update the *Add React to a Website* to in progress. Will try to deliver both by Monday. 😇

cc @pavinthan

**Comment by pavinthan** [comment]
Hey @praveenscience thanks It's already assigned to you. and will update the slack issue.

**Comment by pavinthan** [comment]
@praveenscience try this https://rt-slack-invite.herokuapp.com

**Comment by logesh-kumar** [comment]
Hi @pavinthan I would like to contribute to the topic **Thinking in React**.

**Comment by ratheeps** [comment]
Hi @logesh-kumar 
Thanks for your shown interesting, go ahead with that, please

**Comment by Madhust** [comment]
@pavinthan Please assign **Rendering Elements** to me.

**Comment by dhirajsriram** [comment]
Hey guys, I would like to contribute to the translation. Can I pick a segment?
Mass pannuvom (Let's rock in Tamil) :p

**Comment by pavinthan** [comment]
@dhirajsriram Sure, please pick anything unassigned item in the description list and let us know :)

**Comment by dhirajsriram** [comment]
@pavinthan Can I pick "Conditional Rendering" ?

**Comment by ratheeps** [comment]
Hi @dhirajsriram 
Go ahead with that, please
Thanks.

**Comment by klsv07** [comment]
Hi, 
I would like to contribute as well. I like to take ' Introducing Hooks' first.
I'm unable to click the checkbox to assign. 
Please let me know if u can take the same and assign it to me

Thanks,
Murali.

**Comment by pavinthan** [comment]
thanks @klsv07, please start to work on it, we will check once you done.

**Comment by Ananthakr** [comment]
@pavinthan I would like to pick 'State and Lifecycle'.

**Comment by ratheeps** [comment]
Hi @Ananthakr 
Thanks for your shown interesting, 
Please start to work on "State and Lifecycle" and have updated the checklist.
Thanks

**Comment by mtamilcse92** [comment]
@pavinthan Can i Pick **Composition vs Inheritance** ?

**Comment by pavinthan** [comment]
@mtamilcse92 sure, thanks

**Comment by Pachiyappan** [comment]
Hey guys, I would like to contribute, Can i pick `Handling Events` ?

**Comment by pavinthan** [comment]
@Pachiyappan Yes please

**Comment by mtamilcse92** [comment]
@pavinthan Can i pick **Building Your Own Hooks** ?

**Comment by pavinthan** [comment]
@mtamilcse92 Yes please

**Comment by Pachiyappan** [comment]
@pavinthan I would like to pick `React`. Can i pick?

**Comment by pavinthan** [comment]
Yes, @Pachiyappan please

**Comment by satheeshwaran** [comment]
@pavinthan  @ratheeps @majus28  @GetCodePanda I would like to contribute, can I take up anything under Basics?

**Comment by pavinthan** [comment]
@satheeshwaran Yes, please pick anything under Basics and let us know, we will mark it for you.

thanks 🙂

**Comment by satheeshwaran** [comment]
@pavinthan Let me take Lifting State Up under basics.

**Comment by ratheeps** [comment]
Hi @satheeshwaran please take it, I will mark it for you.

**Comment by kasthuriraajan** [comment]
Hi @pavinthan , @ratheeps , @tesseralis  
I would like to contribute some translations so which one can I take?

**Comment by ratheeps** [comment]
Hi @kasthuriraajan,

Thanks for your shown interestingly.
Would you pick one under "API Reference"? 
Once you picked let us know we will mark it for you.

Thanks.

**Comment by kasthuriraajan** [comment]
Hi @ratheeps , 

I will take "Hooks at a Glance" under "Hooks". Could you please assign me to that task. 

Thanks.

**Comment by saran-io** [comment]
Hello @ratheeps,

I can pick up  Higher-Order Components under advance concepts. Could you put that under my bucket.

**Comment by pavinthan** [comment]
@saran-io Yes sure

**Comment by saran-io** [comment]
> @saran-io Yes sure

Thanks.

**Comment by KiruthikaThangamuthu** [comment]
Hi all, I would like to contribute. Can I pick "Using the State Hook" under "Hooks"?

**Comment by pavinthan** [comment]
@KiruthikaThangamuthu Sure Please,

Thank you

**Comment by pradheepap** [comment]
Hi all, I would like to contribute, Can I pick "Hooks API Reference"?

**Comment by Elcomerz** [comment]
Hi, I Would like to contribute to the **Accessibility** page in  **Advanced Guides**. Shall I?

**Comment by mithelan** [comment]
Hi, would like to contribute, can i pick **Rules of Hooks** ?

**Comment by pavinthan** [comment]
@pradheepap @Elcomerz and @mithelan sure Please,

**Comment by pravee42** [comment]
Hi i would  also like to contribute

**Comment by invisiblegeek1** [comment]
Hi all,

I would like to contribute to this translation effort and can I pick using the effort hook

**Comment by sanjaiyan-dev** [comment]
Hi,

Shall we update the page according to new React 18 and refactor page as same as new [ Reactjs doc](https://beta.reactjs.org/)

**Comment by pravee42** [comment]
Yes we do

**Comment by sanjaiyan-dev** [comment]
> Yes we do

https://github.com/reactjs/ta.reactjs.org/pull/206#issue-1323881604

**Comment by Pachiyappan** [comment]
Yes we do

**Comment by pravee42** [comment]
Hi guys i would like to contribute in the glossary can you please assign me
@pavinthan

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
